apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end

# Create a deployment
# kubectl create -f deployment-definition.yml

# Update the deployment
# kubectl apply -f deployment-definition.yml
# kubectl set image deployment/myapp-deployment nginx-container=nginx:1.9.1

# Delete a deployment
# kubectl delete deployment myapp-deployment

# Get deployment
# kubectl get deployment