apiVersion: v1
kind: Service
metadata:
  name: redis-db

spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379

  selector:
    app: myapp
    type: redis-pod


# Create a service
# kubectl create -f service-definition.yml

# Get service
# kubectl get services
