apiVersion: v1
kind: Service
metadata:
  name: web-service

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: myapp
    type: front-end

# curl http://192.168.1.2:30008